    " 84   AllocColor",
    " 86   AllocColorCells",
    " 87   AllocColorPlanes",
    " 85   AllocNamedColor",
    " 35   AllowEvents",
    "104   Bell",
    " 30   ChangeActivePointerGrab",
    " 56   ChangeGC",
    "109   ChangeHosts",
    "102   ChangeKeyboardControl",
    "100   ChangeKeyboardMapping",
    "105   ChangePointerControl",
    " 18   ChangeProperty",
    "  6   ChangeSaveSet",
    "  2   ChangeWindowAttributes",
    " 13   CirculateWindow",
    " 61   ClearArea",
    " 46   CloseFont",
    " 12   ConfigureWindow",
    " 24   ConvertSelection",
    " 62   CopyArea",
    " 80   CopyColormapAndFree",
    " 57   CopyGC",
    " 63   CopyPlane",
    " 78   CreateColormap",
    " 93   CreateCursor",
    " 55   CreateGC",
    " 94   CreateGlyphCursor",
    " 53   CreatePixmap",
    "  1   CreateWindow",
    " 19   DeleteProperty",
    "  5   DestroySubwindows",
    "  4   DestroyWindow",
    " 69   FillPoly",
    "115   ForceScreenSaver",
    " 79   FreeColormap",
    " 88   FreeColors",
    " 95   FreeCursor",
    " 60   FreeGC",
    " 54   FreePixmap",
    " 17   GetAtomName",
    " 52   GetFontPath",
    " 14   GetGeometry",
    " 73   GetImage",
    " 43   GetInputFocus",
    "103   GetKeyboardControl",
    "101   GetKeyboardMapping",
    "119   GetModifierMapping",
    " 39   GetMotionEvents",
    "106   GetPointerControl",
    "117   GetPointerMapping",
    " 20   GetProperty",
    "108   GetScreenSaver",
    " 23   GetSelectionOwner",
    "  3   GetWindowAttributes",
    " 28   GrabButton",
    " 33   GrabKey",
    " 31   GrabKeyboard",
    " 26   GrabPointer",
    " 36   GrabServer",
    " 77   ImageText16",
    " 76   ImageText8",
    " 81   InstallColormap",
    " 16   InternAtom",
    "113   KillClient",
    " 99   ListExtensions",
    " 49   ListFonts",
    " 50   ListFontsWithInfo",
    "110   ListHosts",
    " 83   ListInstalledColormaps",
    " 21   ListProperties",
    " 92   LookupColor",
    "  9   MapSubwindows",
    "  8   MapWindow",
    "127   NoOperation",
    " 45   OpenFont",
    " 68   PolyArc",
    " 71   PolyFillArc",
    " 70   PolyFillRectangle",
    " 65   PolyLine",
    " 64   PolyPoint",
    " 67   PolyRectangle",
    " 66   PolySegment",
    " 75   PolyText16",
    " 74   PolyText8",
    " 72   PutImage",
    " 97   QueryBestSize",
    " 91   QueryColors",
    " 98   QueryExtension",
    " 47   QueryFont",
    " 44   QueryKeymap",
    " 38   QueryPointer",
    " 48   QueryTextExtents",
    " 15   QueryTree",
    " 96   RecolorCursor",
    "  7   ReparentWindow",
    "114   RotateProperties",
    " 25   SendEvent",
    "111   SetAccessControl",
    " 59   SetClipRectangles",
    "112   SetCloseDownMode",
    " 58   SetDashes",
    " 51   SetFontPath",
    " 42   SetInputFocus",
    "118   SetModifierMapping",
    "116   SetPointerMapping",
    "107   SetScreenSaver",
    " 22   SetSelectionOwner",
    " 89   StoreColors",
    " 90   StoreNamedColor",
    " 40   TranslateCoords",
    " 29   UngrabButton",
    " 34   UngrabKey",
    " 32   UngrabKeyboard",
    " 27   UngrabPointer",
    " 37   UngrabServer",
    " 82   UninstallColormap",
    " 11   UnmapSubwindows",
    " 10   UnmapWindow",
    " 41   WarpPointer",
    NULL
